name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Update to your JDK version
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with: # Update below versions to: platforms;android-${compileSdkVersion} and build-tools;${buildToolsVersion} respectively
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Create AVD
        uses: android-actions/setup-emulator@v1
        with:
          api-level: 34
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window -no-boot-anim &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run JUnit Tests
        run: ./gradlew test

      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk # Verify your APK path